dist: xenial
language: python
python:
  - 3.4
  - 3.5
  - 3.6
  - 3.7
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -y enchant
  - pip install poetry
script:
  - poetry install -v
  - poetry run py.test aeidon
  - poetry run flake8 aeidon
