language: python
python:
  - 3.4
  - 3.5
  - 3.6
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -y enchant
  - pip install chardet flake8 pyenchant
script:
  - flake8 .
  - py.test aeidon
  - python setup.py install
  - python setup.py clean
