language: python
python:
  - 3.3
  - 3.4
  - 3.5
  - 3.6
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -y enchant gettext
  - pip install chardet pyenchant
script:
  - py.test aeidon
  - python setup.py clean
  - python setup.py install --prefix=/tmp/usr
notifications:
  on_success: change
  on_failure: change
