version: ~> 1.0
os: linux
dist: bionic
language: python
python:
  - 3.5
  - 3.6
  - 3.7
before_install:
  - sudo apt-get update -qq
  - sudo apt install -y gir1.2-gspell-1 gir1.2-gtk-3.0 iso-codes xvfb
  - pip install poetry
script:
  - poetry install -v
  - xvfb-run poetry run py.test aeidon
  - poetry run flake8 aeidon
